name: 'dbt_fabric_demo'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=0.17.0"]

profile: 'dbt_fabric_demo'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
